Repository bird-sanctuary/bluejay, pull requests merged in 2023-02, with the labels that each got.

#57 Temperature fix for 1S, updated MCU_48MHZ identifier to MCU_TYPE for clarity
  .gitignore
  BLHeliBootLoad.inc
  Bluejay.asm
  Common.inc
  Layouts/Base.inc
  Makefile
  tools/build.sh
Labels: bug

#48 E-RPM fix
  Bluejay.asm
Labels: bug, enhancement

#64 Implemented diagnostics on status and demag metric frames
  Bluejay.asm
Labels: feature

#68 Artifact PR commenter
  .github/workflows/add_artifact_urls.yml
Labels: chore

#66 chore: Deprecate BB10 MCUs
  Makefile
  README.md
Labels: chore

#74 Scheduler shall generate full telemetry only if it is enabled
  Bluejay.asm
Labels: fix

#75 Hotfix/scheduler demag metric infinite loop
  Bluejay.asm
Labels: fix
