Repository bird-sanctuary/bluejay, pull requests merged in 2023-07, with the labels that each got.

#138 Further reducing motor speed before changing direction in 3D bidirectional mode
  src/Bluejay.asm
Labels: fix

#140 Add happymodel and weebleed to the 'Supporters' section #139
  README.md
Labels: chore

#145 Feature/dynamic pwm
  Makefile
  src/Bluejay.asm
  src/Modules/Common.asm
  src/Modules/Enums.asm
  src/Modules/Isrs.asm
  src/Modules/Settings.asm
  tools/build.sh
Labels: feature

#144 Play custom melody when DSHOT beacon 5 is triggered
  src/Bluejay.asm
  src/Modules/Codespace.asm
  src/Modules/Eeprom.asm
  src/Modules/Fx.asm
Labels: feature

#151 Throttle thresholds were inverted
  src/Modules/Settings.asm
Labels: fix
