Repository bird-sanctuary/bluejay, pull requests merged in 2023-06, with the labels that each got.

#101 Refactored duplicate assignments #99
  src/BLHeliBootLoad.inc
  src/Bluejay.asm
  src/Layouts/A.inc
  src/Layouts/Base.inc
  src/Layouts/C.inc
  src/Layouts/D.inc
  src/Layouts/E.inc
  src/Layouts/F.inc
  src/Layouts/G.inc
  src/Layouts/I.inc
  src/Layouts/J.inc
  src/Layouts/L.inc
  src/Layouts/M.inc
  src/Layouts/O.inc
  src/Layouts/P.inc
  src/Layouts/Q.inc
  src/Layouts/R.inc
  src/Layouts/U.inc
  src/Modules/Codespace.asm
  src/Modules/Common.asm
  src/Modules/Eeprom.asm
  src/Modules/Isrs.asm
  src/Modules/Macros.asm
  src/Modules/Mcus.asm
  src/Modules/Power.asm
  src/Modules/Scheduler.asm
  src/Modules/Settings.asm
  src/Modules/Timing.asm
Labels: chore

#102 Bugfix/reduce scheduler timebase
  src/Bluejay.asm
  src/Layouts/Base.inc
  src/Modules/Isrs.asm
  src/Modules/Scheduler.asm
Labels: fix

#100 Disable temp protection by default #95
  src/Bluejay.asm
Labels: chore

#111 Add EDT safety arm feature
  src/Bluejay.asm
  src/Modules/DShot.asm
  src/Modules/Fx.asm
  src/Modules/Settings.asm
Labels: enhancement

#117 Add ENUM for DSHOT commands
  src/Modules/DShot.asm
  src/Modules/Enums.asm
  src/Modules/Fx.asm
Labels: chore

#116 Refactored MCU spesific offsets so seperate module
  src/BLHeliBootLoad.inc
  src/Bluejay.asm
  src/Modules/Eeprom.asm
  src/Modules/McuOffsets.asm
Labels: chore

#119 Refactored 16 bit division by two into seperate macro #112
  src/Modules/Macros.asm
  src/Modules/Timing.asm
Labels: chore

#124 Bump version number and mark as DEV version #122
  src/Bluejay.asm
Labels: chore

#123 Chore/supporter section 85
  README.md
Labels: chore

#107 Added/improved a couple of comments to better explain what is going on.
  src/Bluejay.asm
  src/Modules/Common.asm
  src/Modules/Commutation.asm
  src/Modules/DShot.asm
  src/Modules/Eeprom.asm
  src/Modules/Fx.asm
  src/Modules/Isrs.asm
  src/Modules/Macros.asm
  src/Modules/Power.asm
  src/Modules/Scheduler.asm
  src/Modules/Settings.asm
  src/Modules/Timing.asm
Labels: chore

#130 Disable dithering by default
  src/Bluejay.asm
Labels: chore

#128 Allow version string to be passed to Makefile via buildscript (for na…
  tools/build.sh
Labels: chore

#132 RC7 tag
  src/Bluejay.asm
Labels: chore
